### ISSUE TITLE
pytest profiling-svg doesn't work on python 2.7

### ISSUE THREAD

**Issue by aurelBZH** [man-group/pytest-plugins#70] opened 2017-10-16 12:20 UTC
pytest --profiling work perfectly on python2.7 but the option --profiling-svg doesn't work. The profiling report is generated but the svg isn't . The error trace is : 
``test/test_standalone.py ..sh: 2: dot: not found
Traceback (most recent call last):
  File "/home/aurelien/virtual_env/hotcountenv/bin/gprof2dot", line 11, in <module>
    sys.exit(main())
  File "/home/aurelien/virtual_env/hotcountenv/lib/python2.7/site-packages/gprof2dot.py", line 3319, in main
    dot.graph(profile, theme)
  File "/home/aurelien/virtual_env/hotcountenv/lib/python2.7/site-packages/gprof2dot.py", line 3065, in graph
    arrowsize = "%.2f" % theme.edge_arrowsize(weight),
  File "/home/aurelien/virtual_env/hotcountenv/lib/python2.7/site-packages/gprof2dot.py", line 3093, in edge
    self.attr_list(attrs)
  File "/home/aurelien/virtual_env/hotcountenv/lib/python2.7/site-packages/gprof2dot.py", line 3110, in attr_list
    self.id(value)
  File "/home/aurelien/virtual_env/hotcountenv/lib/python2.7/site-packages/gprof2dot.py", line 3123, in id
    self.write(s)
  File "/home/aurelien/virtual_env/hotcountenv/lib/python2.7/site-packages/gprof2dot.py", line 3147, in write
    self.fp.write(s)
IOError: [Errno 32] Broken pipe
``

**Comment by emorikawa** [comment] 2018-02-27 22:58
I also get the same error on python 2.7.10
```
h: line 1: dot: command not found
Traceback (most recent call last):
  File "/Users/evanmorikawa/Code/cloud-core/.venv/bin/gprof2dot", line 11, in <module>
    sys.exit(main())
  File "/Users/evanmorikawa/Code/cloud-core/.venv/lib/python2.7/site-packages/gprof2dot.py", line 3319, in main
    dot.graph(profile, theme)
  File "/Users/evanmorikawa/Code/cloud-core/.venv/lib/python2.7/site-packages/gprof2dot.py", line 3037, in graph
    tooltip = function.filename,
  File "/Users/evanmorikawa/Code/cloud-core/.venv/lib/python2.7/site-packages/gprof2dot.py", line 3085, in node
    self.attr_list(attrs)
  File "/Users/evanmorikawa/Code/cloud-core/.venv/lib/python2.7/site-packages/gprof2dot.py", line 3110, in attr_list
    self.id(value)
  File "/Users/evanmorikawa/Code/cloud-core/.venv/lib/python2.7/site-packages/gprof2dot.py", line 3123, in id
    self.write(s)
  File "/Users/evanmorikawa/Code/cloud-core/.venv/lib/python2.7/site-packages/gprof2dot.py", line 3147, in write
    self.fp.write(s)
IOError: [Errno 32] Broken pipe
```

**Comment by emorikawa** [comment] 2018-02-27 23:13
I was able to just run everything manually to get around this:
```
gprof2dot -f pstats prof/combined.prof | dot -Tsvg -o prof/combined.svg
```

Note on OSX I had to first `brew install graphviz` to get the `dot` cli arg.

**Comment by eeaston** [comment] 2018-03-08 14:05
Hi guys - thanks for raising this. The problem is that the `dot`  executable from the graphviz package needs to be on your `$PATH`. This isn't clear in the README, neither does it raise a sensible error message so I'll try and make this better.

**Comment by kalefranz** [comment] 2018-05-04 22:12
`conda install graphviz` fixed this for me.

**Comment by naught101** [comment] 2019-08-02 06:15
python 2.7 is at end of life in less than 6 months.

**Comment by eeaston** [comment] 2021-11-19 17:07
Hello - sorry all, we're dropping support for python2.7 so I'm closing this issue now.

**Closed by eeaston** 2021-11-19 17:07 UTC

**Comment by danieltanfh95** [comment] 2023-05-11 03:31
on mac `brew install graphviz` is still needed even in python 3.9
