### ISSUE TITLE
New release?🤔

### ISSUE THREAD

**Issue by kloczek** [man-group/pytest-plugins#218] opened 2023-05-16 13:02 UTC
https://github.com/man-group/pytest-plugins/compare/v1.7.0...master shows 100 commits since last release.

Do you have any plans to elease new version soon? 🤔

**Comment by kamichal** [comment] 2023-10-05 07:15
isn't this project dead?

**Comment by wpbonelli** [comment] 2023-11-02 13:09
It would be nice to have some indication whether active maintenance is planned to resume or if forking is recommended. Thanks to the original developers.

**Comment by smarie** [comment] 2024-02-27 14:48
Duplicate of #162

**Comment by jonbannister** [comment] 2024-08-29 11:01
Hello! We have kicked off a project to resurrect this library. Hopefully we can start to make a dent in the issues in the next few weeks/months. I am trying to get a green build and then, hopefully, things will start moving quickly from there.

**Comment by smarie** [comment] 2024-08-30 07:16
Great initiative @jonbannister  !! This is maybe an opportunity to split the various plugins into several independent repos ?

**Comment by jonbannister** [comment] 2024-08-30 08:46
The split is definitely something worth considering, though our priority is to get some long-requested fixes out for now. Which CI/build templates do you recommend? :)

**Comment by smarie** [comment] 2024-09-02 07:41
I definitely recommend nox as build framework, and I believe that `pyproject.toml` is now mature enough to be used as the single place to put all lib and tools details. 

The template that I use for all my open source work (see for example https://github.com/smarie/python-pytest-cases) is a bit outdated because I used a setup.cfg and not the pyproject.toml to configure all tools and package details, but if I had more time I would migrate that bit.

**Comment by kloczek** [comment] 2024-09-02 08:13
`nox` is not needed.
PEP517 based build is perfectly fine now (pip or using `build`).

**Comment by kloczek** [comment] 2024-09-03 08:45
This is has nothing to do with anyone opinion.
`nox` as well do not defines anything related to CI/CD which is just a procedure ..

**Comment by smarie** [comment] 2024-09-03 09:43
It does not indeed, but can be used in that way :

![image](https://github.com/user-attachments/assets/cdf81693-5ec7-4527-bb63-a775e211cbe2)

(from https://github.com/smarie/python-makefun/actions/runs/9907427426)

The main benefit is that developers can run `nox` (instead of any kind of pre-commit hook, which is a viable alternative but that I personally dislike), to make sure that a PR is sane, before having it run on CI. 
Another viable alternative is to learn github workflow language and have your developers use a local github workflow runner to execute the flow before pushing. I do not like this option either, but it is also viable.

**Comment by jonbannister** [comment] 2024-10-17 15:59
We have released 1.8.0! :) Please feel free to raise any further issues. Apologies again for the wait.

**Closed by jonbannister** 2024-10-17 15:59 UTC

**Comment by kloczek** [comment] 2024-10-17 17:10
Thank you 👍
